spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Food_ordering
    username: root
    password: 20001024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
